<?xml version="1.0"?>
<GameModel xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Player>
    <_health>69</_health>
    <_maxHealth>100</_maxHealth>
    <_speed>12</_speed>
    <_jumpSpeed>4</_jumpSpeed>
    <_position>
      <x>580.562134</x>
      <y>20.1929531</y>
      <z>338.8589</z>
    </_position>
  </Player>
  <SupplyBox>
    <_position>
      <x>555</x>
      <y>20.3</y>
      <z>342</z>
    </_position>
  </SupplyBox>
  <AmmoBox>
    <_position>
      <x>552</x>
      <y>20.1</y>
      <z>348</z>
    </_position>
  </AmmoBox>
  <AidBoxModel>
    <_position>
      <x>558</x>
      <y>20.3</y>
      <z>346</z>
    </_position>
  </AidBoxModel>
  <ProximityCardModel>
    <_position>
      <x>554</x>
      <y>20.3</y>
      <z>344</z>
    </_position>
  </ProximityCardModel>
  <Bomb>
    <_position>
      <x>553</x>
      <y>20.03</y>
      <z>350</z>
    </_position>
  </Bomb>
</GameModel>